# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git2mite}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Lang", "Thilo Utke", "Robin Mehner"]
  s.date = %q{2010-06-03}
  s.default_executable = %q{git2mite}
  s.email = %q{alex@upstre.am}
  s.executables = ["git2mite"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "README.md",
     "lib/git2mite.rb",
     "lib/git2mite/app.rb",
     "lib/git2mite/configuration.rb",
     "lib/git2mite/git_repo.rb",
     "lib/git2mite/gui.rb",
     "lib/git2mite/mite_client.rb",
     "lib/git2mite/user.rb"
  ]
  s.homepage = %q{http://github.com/upstream/git2mite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{writes your git commit messages to your mite account}
  s.test_files = [
    "spec/configuration_spec.rb",
     "spec/git_repo_spec.rb",
     "spec/gui_spec.rb",
     "spec/mite_client_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
  end
end

